### PR TITLE
Create concatenate.eo

### PR DESCRIPTION
**Pull request by niksgont**

### CODE REVIEW

**Comment by timolai-andrievich** [comment]
- Issue is not linked
- Reviewer is not assigned
- Milestone is not linked
- Project is not linked

**Comment by Graur** [comment]
@niksgont I think here is some kind of problem with indentation (you can check indentation rules [here](https://arxiv.org/abs/2111.13384) p. 2.2 Indentation).

**Review by timolai-andrievich — CHANGES_REQUESTED** [review]
Identation needs to be fixed (2 spaces instead of mix of 4 spaces and tabulations as it is now)

**Review by timolai-andrievich — CHANGES_REQUESTED** [review]
MIT License should be at the top of the file

**Pull request closed without merging**
